/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package me.prince.circe.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockPrice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6803904732023435342L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockPrice\",\"namespace\":\"me.prince.circe.domain\",\"fields\":[{\"name\":\"stockSymbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"date\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<StockPrice> ENCODER =
      new BinaryMessageEncoder<StockPrice>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockPrice> DECODER =
      new BinaryMessageDecoder<StockPrice>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockPrice> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockPrice> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockPrice> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockPrice>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockPrice to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockPrice from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockPrice instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockPrice fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String stockSymbol;
  @Deprecated public double price;
  @Deprecated public java.time.LocalDate date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockPrice() {}

  /**
   * All-args constructor.
   * @param stockSymbol The new value for stockSymbol
   * @param price The new value for price
   * @param date The new value for date
   */
  public StockPrice(java.lang.String stockSymbol, java.lang.Double price, java.time.LocalDate date) {
    this.stockSymbol = stockSymbol;
    this.price = price;
    this.date = date;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stockSymbol;
    case 1: return price;
    case 2: return date;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stockSymbol = value$ != null ? value$.toString() : null; break;
    case 1: price = (java.lang.Double)value$; break;
    case 2: date = (java.time.LocalDate)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stockSymbol' field.
   * @return The value of the 'stockSymbol' field.
   */
  public java.lang.String getStockSymbol() {
    return stockSymbol;
  }


  /**
   * Sets the value of the 'stockSymbol' field.
   * @param value the value to set.
   */
  public void setStockSymbol(java.lang.String value) {
    this.stockSymbol = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public double getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.LocalDate getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.LocalDate value) {
    this.date = value;
  }

  /**
   * Creates a new StockPrice RecordBuilder.
   * @return A new StockPrice RecordBuilder
   */
  public static me.prince.circe.domain.StockPrice.Builder newBuilder() {
    return new me.prince.circe.domain.StockPrice.Builder();
  }

  /**
   * Creates a new StockPrice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockPrice RecordBuilder
   */
  public static me.prince.circe.domain.StockPrice.Builder newBuilder(me.prince.circe.domain.StockPrice.Builder other) {
    if (other == null) {
      return new me.prince.circe.domain.StockPrice.Builder();
    } else {
      return new me.prince.circe.domain.StockPrice.Builder(other);
    }
  }

  /**
   * Creates a new StockPrice RecordBuilder by copying an existing StockPrice instance.
   * @param other The existing instance to copy.
   * @return A new StockPrice RecordBuilder
   */
  public static me.prince.circe.domain.StockPrice.Builder newBuilder(me.prince.circe.domain.StockPrice other) {
    if (other == null) {
      return new me.prince.circe.domain.StockPrice.Builder();
    } else {
      return new me.prince.circe.domain.StockPrice.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockPrice instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockPrice>
    implements org.apache.avro.data.RecordBuilder<StockPrice> {

    private java.lang.String stockSymbol;
    private double price;
    private java.time.LocalDate date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(me.prince.circe.domain.StockPrice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stockSymbol)) {
        this.stockSymbol = data().deepCopy(fields()[0].schema(), other.stockSymbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.price)) {
        this.price = data().deepCopy(fields()[1].schema(), other.price);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing StockPrice instance
     * @param other The existing instance to copy.
     */
    private Builder(me.prince.circe.domain.StockPrice other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.stockSymbol)) {
        this.stockSymbol = data().deepCopy(fields()[0].schema(), other.stockSymbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.price)) {
        this.price = data().deepCopy(fields()[1].schema(), other.price);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'stockSymbol' field.
      * @return The value.
      */
    public java.lang.String getStockSymbol() {
      return stockSymbol;
    }


    /**
      * Sets the value of the 'stockSymbol' field.
      * @param value The value of 'stockSymbol'.
      * @return This builder.
      */
    public me.prince.circe.domain.StockPrice.Builder setStockSymbol(java.lang.String value) {
      validate(fields()[0], value);
      this.stockSymbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stockSymbol' field has been set.
      * @return True if the 'stockSymbol' field has been set, false otherwise.
      */
    public boolean hasStockSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stockSymbol' field.
      * @return This builder.
      */
    public me.prince.circe.domain.StockPrice.Builder clearStockSymbol() {
      stockSymbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public double getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public me.prince.circe.domain.StockPrice.Builder setPrice(double value) {
      validate(fields()[1], value);
      this.price = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public me.prince.circe.domain.StockPrice.Builder clearPrice() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.time.LocalDate getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public me.prince.circe.domain.StockPrice.Builder setDate(java.time.LocalDate value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public me.prince.circe.domain.StockPrice.Builder clearDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockPrice build() {
      try {
        StockPrice record = new StockPrice();
        record.stockSymbol = fieldSetFlags()[0] ? this.stockSymbol : (java.lang.String) defaultValue(fields()[0]);
        record.price = fieldSetFlags()[1] ? this.price : (java.lang.Double) defaultValue(fields()[1]);
        record.date = fieldSetFlags()[2] ? this.date : (java.time.LocalDate) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockPrice>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockPrice>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockPrice>
    READER$ = (org.apache.avro.io.DatumReader<StockPrice>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










